### PR TITLE
Star detail

### PR DESCRIPTION
**Pull request by DanielAndreasen**
A detailed page for a star. Reached by going to **localhost:5000/starname**. For example **localhost:5000/HD 202206** (spaces are allowed). This has been requested in issue #29.

- [x] Make the routing to the page work
- [x] Write the stellar information
- [x] Add link to Simbad
- [x] Add link to exoplanetEU
- [x] Merge with exoplanetEU (_easy_)
- [x] Loop through the exoplanets and write that to the page (_intermediate_)
- [x] Available by clicking the stellar name in the table (_easy_)

### CODE REVIEW

**Comment by jason-neal** [comment]
So you want to direct them to our "details" page rather than SIMBAD. (last point)?

**Comment by DanielAndreasen** [comment]
I am not sure about the last point. Maybe being able to direct to Simbad from the detailed page?

**Comment by jason-neal** [comment]
Sounds good. Could then add both the Simbad link and the exoplanet EU link.

**Comment by DanielAndreasen** [comment]
Good idea. I added the checkboxes on that.

**Comment by DanielAndreasen** [comment]
Not sure what to do about the stars that does not exists (I write about this in #29). Basically the ExoplanetEU star name and SC star name does not match up.

**Comment by jason-neal** [comment]
Just looking at the `hz1`, `hz2` values and I took from the code that...
- hz1 (the inner boundary) is given by `hz` with `model=2`, which corresponds to "# Runaway greenhouse parameters"
- hz2 (the outer boundary) is given by `hz `with `model=4`, which corresponds to "# Maximum greenhouse parameters"

- There is no user choice to select the hz model (e.g. Mars, Venus) (Not suggesting that there should be)

Is this what it is supposed to do?

**Comment by DanielAndreasen** [comment]
I think for now, that is fine. We can consider doing something more sophisticated. This is also just a prrof of concept of what can be done.
I'm just cleanin up the code a little, so there will come a commit soon. This will probably be the last commit for this PR.

**Comment by DanielAndreasen** [comment]
If you can have a look at some point and open a few of the stars. Some won't show planetary details anymore, because the merge failed. What do you think?

**Comment by jason-neal** [comment]
I don't know if it is supposed to do this but when the browser width is reduced the planet parameters drop underneath the stellar parameters. 

I do see that some don't show planetary parameters (python2). On python3 these cause an attribute error. `AttributeError: 'str' object has no attribute 'decode'` 
in this line `d['plName'] = list(map(lambda s: s.decode(), d['plName']))` but I can fix this later.

Have you considered list comprehensions rather than list map and lambda?
e.g. here `d['plName'] = [s.decode() for s in d['plName']]`
This won't solve the decode issue here but is more "pythonic" and I find easier to read.

I like how the star and planet names link to the simbad and exoplanetEU

**Comment by jason-neal** [comment]
`Other informations`  -> `Other information`  or `Other info`

**Comment by DanielAndreasen** [comment]
For the decode part: this is done because it's loaded as bytes I think. And using decode will change it to str. I guess we can just check the type of plName before trying to use decode.

**Comment by DanielAndreasen** [comment]
Didn't have any plans for how it should look like when the browser width is reduced

**Comment by jason-neal** [comment]
Fixed the s.decode part. added a conditional  ` s.decode if isinstance(s, bytes) esle s`

In python2
   - `isistance(s, str) = isinstance(s, bytes) = True`, 

but in python3
  -  `isinstance(s,bytes)=False`

**Comment by DanielAndreasen** [comment]
Is everything ready to merge?

**Comment by jason-neal** [comment]
Yes I think so.

**Pull request merged**
