### PR TITLE
Update to ExoplanetEU2

### PR DESCRIPTION
**Pull request by DanielAndreasen**
Use `ExoplanetEU2` and rename relevant columns to avoid conflicting names.
This will resolve issue #31

### CODE REVIEW

**Comment by jason-neal** [comment]
So you would like me to check this and merge if it is fine?

**Comment by DanielAndreasen** [comment]
I was mostly just playing around with github and PRs, but that would be nice :)

**Comment by jason-neal** [comment]
Yea seems good.

**Comment by DanielAndreasen** [comment]
A zero-correlation is also good to show sometimes, I guess. You can be sure people will request the impact parameter if it is not there.

**Pull request merged**
