### PR TITLE
Round to 2 decimals.  #54

### PR DESCRIPTION
**Pull request by jason-neal**
#54 This rounds all the data columns except `teff `and `tefferr` which are to be `int`, to 2 dp.

It could also have been done as
```
decimals = {'Vmag': 2, 'Vmagerr': 2, 'par': 2, 'parerr': 2, 'logg': 2, 'loggerr': 2,
+                'logglc': 2, 'logglcerr': 2, 'vt': 2, 'vterr': 2, 'feh': 2, 'feherr': 2,
+                'mass': 2, 'masserr': 2}
dfs = dfs.round(decimals)
```
maybe in `inplace=True` would also work
`dfs.round(decimals, inplace=True)`
At the time I didn't want to repeat all the 2's but seeing this here it may be better then using the for loop.
Do you have a preference?

### CODE REVIEW

**Comment by DanielAndreasen** [comment]
I have no preference. If this work as expected then we can merge and close

**Comment by jason-neal** [comment]
I think I found a better way. I will try it tonight
```
decimals = dict.fromkeys(['Vmag', 'Vmagerr', 'par', 'parerr': 2, 'logg'], 2)
dfs = dfs.round(decimals)
```

**Comment by DanielAndreasen** [comment]
I think you can just do a dictionary comprehension (like list comprehension), if you want to save some lines of code.

**Comment by jason-neal** [comment]
Yes I just looked it up it would be
`decimals = {key: 2 for key in ['Vmag', 'Vmagerr', 'par', 'parerr', 'logg' ...]}`
From the code alone I think the the `dict.from_keys` line is nicer.

**Comment by DanielAndreasen** [comment]
I'm okay with both solutions. Feel free to merge when you have implemented whichever you prefer :)

**Pull request merged**
